
services:
  # 1. RUN Redis Server
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - queue-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: queue
    ports:
      - "3306:3306"
    networks:
      - queue-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  # 2. RUN Producer (API)
  producer:
    build: .                 # Build Dockerfile current file
    image: hduc2412/go-queue-app:v1
    command: ["./producer-app"] # CMD RUN Producer
    ports:
      - "8080:8080"          # public port 8080 outside to call API
    environment:
      - REDIS_ADDR=redis:6379
    networks:
      - queue-network
    depends_on:
      - redis                #  Wait Redis run completely before running producer

#Run WORKER
  worker:
    build: .
    image: hduc2412/go-queue-app:v1
    command: ["./worker-app"] 
    ports:
      - "8082:8082" # port promethues metrics  
    environment:
      - REDIS_ADDR=redis:6379
      - POD_NAME=worker-node-1
      - MYSQL_DSN=root:root@tcp(mysql:3306)/queue?parseTime=true
    networks:
      - queue-network
    depends_on:
      redis:
        condition: service_started
      mysql:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - queue-network # make sure using cluster network with redis and producer

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # password default
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    networks:
      - queue-network

networks:
  queue-network:
    driver: bridge
