apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-worker-deployment
  labels:
    app: queue-worker
spec:
  # the number of replicas default is 1, KEDA will auto scale increase/decrease 1-10 base on queue
  selector:
    matchLabels:
      app: queue-worker
  template:
    metadata:
      labels:
        app: queue-worker
    spec:
      containers:
      - name: worker
        image: hduc2412/go-queue-app:v1 
        command: ["./worker-app"]             
        env:
        - name: REDIS_ADDR
          value: "redis-service:6379"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name 