apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: redis-worker-scaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: queue-worker-deployment
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: redis-streams
      metadata:
        address: redis-service.default.svc.cluster.local:6379
        stream: task_stream
        consumerGroup: worker_group
        lagCount: "20"
        activationLagCount: "0"
